// This file is automatically generated. Do not edit it directly.

import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    process.env.SUPABASE_URL;

  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY
        ? ["SUPABASE_PUBLISHABLE_KEY"]
        : []),
    ];

    const message = `Missing Supabase environment variable(s): ${missing.join(
      ", "
    )}`;

    console.error("[Supabase]", message);

    throw new Error(message);
  }

  const client = createClient<Database>(
    SUPABASE_URL,
    SUPABASE_PUBLISHABLE_KEY,
    {
      auth: {
        storage:
          typeof window !== "undefined"
            ? window.localStorage
            : undefined,

        persistSession: true,
        autoRefreshToken: true,
        detectSessionInUrl: false,
      },
    }
  );

  // DEBUG CHECK
  client.storage.listBuckets().then(({ data, error }) => {
    console.log("SUPABASE URL:", SUPABASE_URL);
    console.log("BUCKETS:", data);
    console.log("BUCKET ERROR:", error);
  });

  return client;
}

let _supabase:
  | ReturnType<typeof createSupabaseClient>
  | undefined;

// Import like:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = new Proxy(
  {} as ReturnType<typeof createSupabaseClient>,
  {
    get(_, prop, receiver) {
      if (!_supabase) {
        _supabase = createSupabaseClient();
      }

      return Reflect.get(_supabase, prop, receiver);
    },
  }
);
